import { z } from 'zod';
import { LOCALES, LOCALE_INFO, type Locale } from './i18n.js';
import { DEFAULT_OG_CARD, ogCardSchema, type OgCard } from './og-card.js';
import { DEFAULT_CAPTCHA_CONFIG, captchaConfigSchema, type CaptchaConfig } from './captcha.js';
import { DEFAULT_MAINTENANCE_PAGE, maintenancePageSchema, type MaintenancePage } from './maintenance-page.js';

/**
 * Ayar kayıt defteri. Veritabanında (`settings` tablosu) yalnızca varsayılandan farklı değerler tutulur.
 * Admin paneli bu tanımlardan form üretir; `public: true` olanlar istemciye de gönderilir.
 */

export type SettingInput = 'text' | 'textarea' | 'number' | 'boolean' | 'select' | 'list';

export interface SettingDefinition<S extends z.ZodType = z.ZodType> {
  section: SettingSection;
  schema: S;
  default: z.infer<S>;
  label: string;
  description?: string;
  input: SettingInput;
  options?: { value: string; label: string }[];
  /** İstemciye (herkese) açık mı? */
  public?: boolean;
  /** Admin formunda gösterilmez (iç durum). */
  hidden?: boolean;
}

export const SETTING_SECTIONS = {
  general: 'Genel',
  registration: 'Kayıt',
  security: 'Güvenlik',
  email: 'E-posta',
  profile: 'Profil',
  avatars: 'Avatarlar',
  signatures: 'İmzalar',
  warnings: 'Uyarılar',
  achievements: 'Başarılar',
  forum: 'Forum',
  appearance: 'Görünüm',
  cookies: 'Çerezler',
  messages: 'Özel mesajlar',
  wiki: 'Wiki',
  tickets: 'Destek talepleri',
  seo: 'Arama motorları ve paylaşım',
  language: 'Dil',
} as const;

/** Yönetim panelinden seçilebilen yazı tipleri (hepsi Türkçe karakter destekli, değişken ağırlıklı). */
/** Forum temaları (Yönetim → Görünüm → Tema) */
export const THEME_STYLES = ['modern', 'community'] as const;
export type ThemeStyle = (typeof THEME_STYLES)[number];

export const FONT_OPTIONS = [
  { key: 'roboto', label: 'Roboto', family: "'Roboto Variable'" },
  { key: 'inter', label: 'Inter', family: "'Inter Variable'" },
  { key: 'open-sans', label: 'Open Sans', family: "'Open Sans Variable'" },
  { key: 'rubik', label: 'Rubik', family: "'Rubik Variable'" },
  { key: 'nunito', label: 'Nunito', family: "'Nunito Variable'" },
  { key: 'manrope', label: 'Manrope', family: "'Manrope Variable'" },
  { key: 'montserrat', label: 'Montserrat', family: "'Montserrat Variable'" },
  { key: 'outfit', label: 'Outfit', family: "'Outfit Variable'" },
  { key: 'figtree', label: 'Figtree', family: "'Figtree Variable'" },
] as const;
export type FontKey = (typeof FONT_OPTIONS)[number]['key'];

/** Alt bilgi bağlantısı adresi: site içi yol, http(s) ya da mailto. */
const footerLinkUrl = z
  .string()
  .trim()
  .max(500)
  .regex(/^(https?:\/\/|\/|mailto:)/i, 'Adres http(s)://, / ya da mailto: ile başlamalı.');

export const SOCIAL_PLATFORMS = [
  { key: 'discord', label: 'Discord' },
  { key: 'instagram', label: 'Instagram' },
  { key: 'youtube', label: 'YouTube' },
  { key: 'x', label: 'X (Twitter)' },
  { key: 'facebook', label: 'Facebook' },
  { key: 'tiktok', label: 'TikTok' },
  { key: 'twitch', label: 'Twitch' },
  { key: 'kick', label: 'Kick' },
  { key: 'telegram', label: 'Telegram' },
  { key: 'whatsapp', label: 'WhatsApp' },
  { key: 'reddit', label: 'Reddit' },
  { key: 'linkedin', label: 'LinkedIn' },
  { key: 'github', label: 'GitHub' },
  { key: 'spotify', label: 'Spotify' },
  { key: 'steam', label: 'Steam' },
  { key: 'website', label: 'Web sitesi' },
] as const;
export type SocialPlatform = (typeof SOCIAL_PLATFORMS)[number]['key'];

const assetUrl = z.string().max(500).regex(/^(\/|https:\/\/)/, 'Geçersiz adres.').nullable();
export type SettingSection = keyof typeof SETTING_SECTIONS;

function def<S extends z.ZodType>(d: SettingDefinition<S>): SettingDefinition<S> {
  return d;
}

export const REGISTRATION_MODES = ['open', 'email', 'approval', 'email_approval', 'closed'] as const;
export type RegistrationMode = (typeof REGISTRATION_MODES)[number];

export const SETTINGS = {
  // Genel
  'general.forumName': def({
    section: 'general',
    schema: z.string().trim().min(1).max(80),
    default: 'Forum',
    label: 'Forum adı',
    input: 'text',
    public: true,
  }),
  'general.forumDescription': def({
    section: 'general',
    schema: z.string().trim().max(300),
    default: 'Topluluğumuza hoş geldiniz.',
    label: 'Forum açıklaması',
    input: 'textarea',
    public: true,
  }),
  'updates.config': def({
    section: 'general',
    schema: z.record(z.string(), z.unknown()),
    default: {} as Record<string, unknown>,
    label: 'Güncelleme ayarları',
    input: 'list',
    hidden: true,
  }),
  /** Coolify Deploy Webhook ile güncelleme: { webhookUrl, tokenEnc } */
  'updates.coolify': def({
    section: 'general',
    schema: z.record(z.string(), z.unknown()),
    default: {} as Record<string, unknown>,
    label: 'Coolify güncelleme bağlantısı',
    input: 'list',
    hidden: true,
  }),
  /** Alt bilgideki "InkForum ile çalışır" bağlantısı */
  'appearance.poweredBy': def({
    section: 'appearance',
    schema: z.boolean(),
    default: true,
    label: 'Alt bilgide "InkForum" bağlantısını göster',
    input: 'boolean',
    public: true,
  }),
  'maintenance.autoBackup': def({
    section: 'general',
    schema: z.boolean(),
    default: true,
    label: 'Günlük otomatik veritabanı yedeği',
    input: 'boolean',
    hidden: true,
  }),
  'maintenance.backupKeep': def({
    section: 'general',
    schema: z.number().int().min(1).max(60),
    default: 7,
    label: 'Saklanacak yedek sayısı',
    input: 'number',
    hidden: true,
  }),
  'seo.indexing': def({
    section: 'seo',
    schema: z.boolean(),
    default: true,
    label: 'Arama motorları siteyi dizinlesin',
    description: 'Kapalıyken robots.txt tüm siteyi engeller ve sayfalara "noindex" eklenir (kurulum / test aşaması için).',
    input: 'boolean',
    public: true,
  }),
  'seo.indexProfiles': def({
    section: 'seo',
    schema: z.boolean(),
    default: false,
    label: 'Üye profilleri arama sonuçlarında görünsün',
    input: 'boolean',
    public: true,
  }),
  'seo.ogImages': def({
    section: 'seo',
    schema: z.boolean(),
    default: true,
    label: 'Paylaşım görsellerini otomatik üret',
    description: 'Konular Discord, X, WhatsApp gibi yerlerde paylaşılınca başlık ve bilgilerle özel bir kart görseli oluşturulur (sunucuda sharp gerekir; yoksa logo/banner kullanılır).',
    input: 'boolean',
    public: true,
  }),
  'seo.ogCard': def({
    section: 'seo',
    schema: ogCardSchema,
    default: DEFAULT_OG_CARD as OgCard,
    label: 'Paylaşım kartı tasarımı',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'seo.twitterHandle': def({
    section: 'seo',
    schema: z.string().trim().max(30).regex(/^@?[A-Za-z0-9_]*$/, 'Yalnızca kullanıcı adı (ör. @forumadi).'),
    default: '',
    label: 'X (Twitter) hesabı',
    input: 'text',
    public: true,
  }),
  'seo.googleVerification': def({
    section: 'seo',
    schema: z.string().trim().max(120).regex(/^[A-Za-z0-9_-]*$/, 'Yalnızca doğrulama kodunu girin.'),
    default: '',
    label: 'Google Search Console doğrulama kodu',
    description: 'HTML etiketi yöntemindeki content değeri.',
    input: 'text',
    public: true,
  }),
  'seo.bingVerification': def({
    section: 'seo',
    schema: z.string().trim().max(120).regex(/^[A-Za-z0-9_-]*$/, 'Yalnızca doğrulama kodunu girin.'),
    default: '',
    label: 'Bing Webmaster doğrulama kodu',
    input: 'text',
    public: true,
  }),
  'seo.yandexVerification': def({
    section: 'seo',
    schema: z.string().trim().max(120).regex(/^[A-Za-z0-9_-]*$/, 'Yalnızca doğrulama kodunu girin.'),
    default: '',
    label: 'Yandex Webmaster doğrulama kodu',
    input: 'text',
    public: true,
  }),
  'seo.robotsExtra': def({
    section: 'seo',
    schema: z.string().max(5000),
    default: '',
    label: 'robots.txt ek kurallar',
    description: 'Varsayılan kuralların sonuna eklenir. Örn. "User-agent: GPTBot" + "Disallow: /" ile yapay zekâ tarayıcılarını engelleyebilirsiniz.',
    input: 'textarea',
  }),
  'seo.blockAiCrawlers': def({
    section: 'seo',
    schema: z.boolean(),
    default: false,
    label: 'Yapay zekâ eğitim tarayıcılarını engelle',
    description: 'GPTBot, ClaudeBot, CCBot, Google-Extended ve benzerleri robots.txt ile engellenir.',
    input: 'boolean',
  }),
  'maintenance.backupHour': def({
    section: 'general',
    schema: z.number().int().min(0).max(23),
    default: 3,
    label: 'Günlük yedek saati',
    input: 'number',
    hidden: true,
  }),
  'maintenance.backupKind': def({
    section: 'general',
    schema: z.enum(['db', 'sql', 'full']),
    default: 'db' as 'db' | 'sql' | 'full',
    label: 'Günlük yedek türü',
    input: 'select',
    hidden: true,
  }),
  'i18n.defaultLocale': def({
    section: 'language',
    schema: z.enum(LOCALES),
    default: 'tr' as Locale,
    label: 'Varsayılan dil',
    description: 'Tarayıcı dili desteklenmiyorsa ve üye kendi dilini seçmediyse kullanılır.',
    input: 'select',
    options: LOCALES.map((l) => ({ value: l, label: LOCALE_INFO[l].name })),
    public: true,
  }),
  'i18n.enabledLocales': def({
    section: 'language',
    schema: z.array(z.enum(LOCALES)).min(1),
    // Çevirisi tamamlanan diller (diğer kataloglar yarım; tamamlanınca bu listeye eklenir)
    default: ['tr', 'en'] as Locale[],
    label: 'Kullanılabilir diller',
    description: 'Üyelerin seçebileceği diller.',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'i18n.detectBrowser': def({
    section: 'language',
    schema: z.boolean(),
    default: true,
    label: 'Tarayıcı dilini otomatik algıla',
    description: 'Kapalıyken dil seçmemiş herkes varsayılan dili görür.',
    input: 'boolean',
    public: true,
  }),
  'waf.config': def({
    section: 'security',
    schema: z.record(z.string(), z.unknown()),
    default: {} as Record<string, unknown>,
    label: 'Güvenlik duvarı',
    input: 'list',
    hidden: true,
  }),
  'captcha.config': def({
    section: 'security',
    schema: captchaConfigSchema,
    default: DEFAULT_CAPTCHA_CONFIG as CaptchaConfig,
    label: 'Doğrulama (captcha)',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'captcha.secretEnc': def({
    section: 'security',
    schema: z.string().max(2000),
    default: '',
    label: 'Captcha gizli anahtarı',
    input: 'text',
    hidden: true,
  }),
  'waf.secretEnc': def({
    section: 'security',
    schema: z.string().max(2000),
    default: '',
    label: 'Doğrulama gizli anahtarı',
    input: 'text',
    hidden: true,
  }),
  'plugins.enabled': def({
    section: 'general',
    schema: z.record(z.string(), z.boolean()),
    default: { landing: true, wiki: true, applications: true, tickets: true } as Record<string, boolean>,
    label: 'Eklentiler',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'appearance.themeId': def({
    section: 'appearance',
    schema: z.number().int().nullable(),
    default: null as number | null,
    label: 'Etkin tema',
    input: 'number',
    hidden: true,
  }),
  'appearance.theme': def({
    section: 'appearance',
    schema: z.unknown(),
    default: null as unknown,
    label: 'Etkin tema (derlenmiş)',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'shoutbox.config': def({
    section: 'general',
    schema: z.object({ maxLength: z.number().int(), history: z.number().int(), guests: z.boolean() }),
    default: { maxLength: 300, history: 30, guests: true },
    label: 'Sohbet kutusu',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'discord.config': def({
    section: 'general',
    schema: z.object({ webhookEnc: z.string(), boardIds: z.array(z.number().int()), replies: z.boolean(), guildId: z.string(), inviteUrl: z.string() }),
    default: { webhookEnc: '', boardIds: [] as number[], replies: false, guildId: '', inviteUrl: '' },
    label: 'Discord',
    input: 'list',
    hidden: true,
  }),
  'tickets.maxOpenPerUser': def({
    section: 'tickets',
    schema: z.number().int().min(1).max(100),
    default: 5,
    label: 'Üye başına açık talep sınırı',
    description: 'Bir üyenin aynı anda açık tutabileceği en fazla destek talebi.',
    input: 'number',
    public: true,
  }),
  'tickets.seeded': def({
    section: 'tickets',
    schema: z.boolean(),
    default: false,
    label: 'Varsayılan destek kategorileri oluşturuldu',
    input: 'boolean',
    hidden: true,
  }),
  'tickets.allowUserClose': def({
    section: 'tickets',
    schema: z.boolean(),
    default: true,
    label: 'Üyeler kendi taleplerini kapatabilir',
    input: 'boolean',
    public: true,
  }),
  'home.landingPage': def({
    section: 'general',
    schema: z.string().trim().max(60),
    default: '',
    label: 'Açılış sayfası',
    description: 'Ana sayfada gösterilecek özel sayfanın adresi. Boşsa ana sayfa forum dizinidir; doluysa forum /forum adresine taşınır.',
    input: 'text',
    public: true,
    hidden: true,
  }),
  'wiki.enabled': def({
    section: 'wiki',
    schema: z.boolean(),
    default: true,
    label: 'Wiki açık',
    description: 'Kapalıyken /wiki adresi yalnızca düzenleme yetkisi olanlara görünür.',
    input: 'boolean',
    public: true,
  }),
  'wiki.title': def({
    section: 'wiki',
    schema: z.string().trim().min(1).max(60),
    default: 'Wiki',
    label: 'Wiki adı',
    description: 'Ör. "Rehber", "Bilgi Bankası", "Sunucu Wikisi".',
    input: 'text',
    public: true,
  }),
  'wiki.description': def({
    section: 'wiki',
    schema: z.string().trim().max(300),
    default: 'Rehberler, kurallar ve sık sorulan sorular.',
    label: 'Wiki açıklaması',
    input: 'textarea',
    public: true,
  }),
  'general.maintenanceMode': def({
    section: 'general',
    schema: z.boolean(),
    default: false,
    label: 'Bakım modu',
    description: 'Açıkken yalnızca yöneticiler foruma erişebilir.',
    input: 'boolean',
    public: true,
  }),
  'general.maintenanceMessage': def({
    section: 'general',
    schema: z.string().trim().max(1000),
    default: 'Forum kısa bir süreliğine bakımda. Lütfen daha sonra tekrar deneyin.',
    label: 'Bakım mesajı',
    input: 'textarea',
    public: true,
  }),
  'general.maintenancePage': def({
    section: 'general',
    schema: maintenancePageSchema,
    default: DEFAULT_MAINTENANCE_PAGE as MaintenancePage,
    label: 'Bakım sayfası',
    input: 'list',
    public: true,
    hidden: true,
  }),

  // Kayıt
  'registration.mode': def({
    section: 'registration',
    schema: z.enum(REGISTRATION_MODES),
    default: 'email' as RegistrationMode,
    label: 'Kayıt yöntemi',
    input: 'select',
    options: [
      { value: 'open', label: 'Anında kayıt' },
      { value: 'email', label: 'E-posta doğrulaması' },
      { value: 'approval', label: 'Yönetici onayı' },
      { value: 'email_approval', label: 'E-posta doğrulaması + yönetici onayı' },
      { value: 'closed', label: 'Kayıtlar kapalı' },
    ],
    public: true,
  }),
  'registration.minAge': def({
    section: 'registration',
    schema: z.number().int().min(0).max(99),
    default: 13,
    label: 'Minimum yaş',
    description: '0 ise yaş kontrolü yapılmaz.',
    input: 'number',
    public: true,
  }),
  'registration.requireBirthdate': def({
    section: 'registration',
    schema: z.boolean(),
    default: false,
    label: 'Kayıtta doğum tarihi zorunlu',
    input: 'boolean',
    public: true,
  }),
  'registration.usernameMinLength': def({
    section: 'registration',
    schema: z.number().int().min(1).max(25),
    default: 3,
    label: 'Kullanıcı adı en az uzunluk',
    input: 'number',
    public: true,
  }),
  'registration.usernameMaxLength': def({
    section: 'registration',
    schema: z.number().int().min(3).max(50),
    default: 25,
    label: 'Kullanıcı adı en fazla uzunluk',
    input: 'number',
    public: true,
  }),
  'registration.reservedNames': def({
    section: 'registration',
    schema: z.array(z.string().trim().min(1).max(50)).max(500),
    default: ['admin', 'administrator', 'yönetici', 'moderator', 'moderatör', 'root', 'system', 'sistem', 'destek', 'support'],
    label: 'Rezerve isimler',
    description: 'Bu isimler (veya bunları içeren isimler) kullanılamaz. Her satıra bir isim.',
    input: 'list',
  }),
  'registration.reservedNamesContains': def({
    section: 'registration',
    schema: z.boolean(),
    default: true,
    label: 'Rezerve isim içeren adları da engelle',
    input: 'boolean',
  }),
  'registration.minSubmitSeconds': def({
    section: 'registration',
    schema: z.number().int().min(0).max(120),
    default: 3,
    label: 'Formun gönderilebileceği en kısa süre (sn)',
    description: 'Bot koruması: formu bu süreden hızlı gönderenler reddedilir.',
    input: 'number',
  }),

  // Güvenlik
  'security.passwordMinLength': def({
    section: 'security',
    schema: z.number().int().min(6).max(128),
    default: 8,
    label: 'Şifre en az uzunluk',
    input: 'number',
    public: true,
  }),
  'security.passwordRequireMixed': def({
    section: 'security',
    schema: z.boolean(),
    default: true,
    label: 'Şifrede harf ve rakam zorunlu',
    input: 'boolean',
    public: true,
  }),
  'security.loginMaxAttempts': def({
    section: 'security',
    schema: z.number().int().min(3).max(100),
    default: 5,
    label: 'Kilitlenmeden önce hatalı giriş sayısı',
    input: 'number',
  }),
  'security.loginLockoutMinutes': def({
    section: 'security',
    schema: z.number().int().min(1).max(1440),
    default: 15,
    label: 'Kilitlenme süresi (dk)',
    input: 'number',
  }),
  'security.sessionIdleHours': def({
    section: 'security',
    schema: z.number().int().min(1).max(720),
    default: 12,
    label: '"Beni hatırla" seçilmediğinde oturum süresi (saat)',
    input: 'number',
  }),
  'security.rememberDays': def({
    section: 'security',
    schema: z.number().int().min(1).max(365),
    default: 30,
    label: '"Beni hatırla" oturum süresi (gün)',
    input: 'number',
  }),
  'security.adminElevationMinutes': def({
    section: 'security',
    schema: z.number().int().min(5).max(240),
    default: 30,
    label: 'Yönetim paneli yeniden doğrulama süresi (dk)',
    input: 'number',
  }),

  // E-posta
  'email.fromName': def({
    section: 'email',
    schema: z.string().trim().min(1).max(80),
    default: 'Forum',
    label: 'Gönderen adı',
    input: 'text',
  }),
  'email.fromAddress': def({
    section: 'email',
    schema: z.email(),
    default: 'noreply@example.com',
    label: 'Gönderen adresi',
    input: 'text',
  }),
  'email.verifyTokenHours': def({
    section: 'email',
    schema: z.number().int().min(1).max(720),
    default: 48,
    label: 'Doğrulama bağlantısı geçerlilik süresi (saat)',
    input: 'number',
  }),
  'email.resetTokenMinutes': def({
    section: 'email',
    schema: z.number().int().min(5).max(1440),
    default: 60,
    label: 'Şifre sıfırlama bağlantısı geçerlilik süresi (dk)',
    input: 'number',
  }),
  'mail.transport': def({
    section: 'email',
    schema: z.object({
      driver: z.enum(['env', 'smtp', 'sendmail', 'log']),
      host: z.string().max(200),
      port: z.number().int().min(1).max(65535),
      security: z.enum(['starttls', 'tls', 'none']),
      user: z.string().max(200),
      passwordEnc: z.string().max(2000),
      allowSelfSigned: z.boolean(),
    }),
    default: { driver: 'env', host: '', port: 587, security: 'starttls', user: '', passwordEnc: '', allowSelfSigned: false } as {
      driver: 'env' | 'smtp' | 'sendmail' | 'log';
      host: string;
      port: number;
      security: 'starttls' | 'tls' | 'none';
      user: string;
      passwordEnc: string;
      allowSelfSigned: boolean;
    },
    label: 'E-posta gönderim ayarları',
    input: 'list',
    hidden: true,
  }),
  'email.welcome': def({
    section: 'email',
    schema: z.boolean(),
    default: true,
    label: 'Hesap etkinleşince hoş geldin e-postası gönder',
    description: 'Şablon: Yönetim → E-posta → Şablonlar → Hoş geldin.',
    input: 'boolean',
  }),
  'email.notifications': def({
    section: 'email',
    schema: z.boolean(),
    default: true,
    label: 'Bildirim e-postaları',
    description: 'Alıntı, bahsetme, takip edilen konuya yanıt ve özel mesajlar için e-posta (üye kendi ayarlarından kapatabilir).',
    input: 'boolean',
  }),

  // Profil
  'profile.usernameChangeCooldownDays': def({
    section: 'profile',
    schema: z.number().int().min(0).max(3650),
    default: 30,
    label: 'Kullanıcı adı değişiklikleri arası bekleme (gün)',
    input: 'number',
    public: true,
  }),
  'profile.coversEnabled': def({
    section: 'profile',
    schema: z.boolean(),
    default: true,
    label: 'Profil kapak fotoğrafları açık',
    input: 'boolean',
    public: true,
  }),
  'profile.coverMaxKb': def({
    section: 'profile',
    schema: z.number().int().min(100).max(20480),
    default: 4096,
    label: 'Kapak fotoğrafı en fazla boyut (KB)',
    input: 'number',
    public: true,
  }),
  'profile.bioMaxLength': def({
    section: 'profile',
    schema: z.number().int().min(0).max(10000),
    default: 1000,
    label: 'Hakkımda en fazla uzunluk',
    input: 'number',
    public: true,
  }),
  'profile.customTitleMaxLength': def({
    section: 'profile',
    schema: z.number().int().min(0).max(100),
    default: 40,
    label: 'Özel başlık en fazla uzunluk',
    input: 'number',
    public: true,
  }),

  // Avatarlar
  'avatars.enabled': def({
    section: 'avatars',
    schema: z.boolean(),
    default: true,
    label: 'Avatar yüklemeleri açık',
    input: 'boolean',
    public: true,
  }),
  'avatars.maxSizeKb': def({
    section: 'avatars',
    schema: z.number().int().min(16).max(10240),
    default: 512,
    label: 'En büyük avatar dosyası (KB)',
    input: 'number',
    public: true,
  }),
  'avatars.size': def({
    section: 'avatars',
    schema: z.number().int().min(64).max(1024),
    default: 256,
    label: 'Avatar boyutu (px)',
    description: 'Yüklenen avatarlar bu boyuta küçültülür.',
    input: 'number',
    public: true,
  }),

  // İmzalar
  'signatures.enabled': def({
    section: 'signatures',
    schema: z.boolean(),
    default: true,
    label: 'İmzalar açık',
    input: 'boolean',
    public: true,
  }),
  'signatures.maxLength': def({
    section: 'signatures',
    schema: z.number().int().min(0).max(5000),
    default: 500,
    label: 'İmza en fazla karakter',
    input: 'number',
    public: true,
  }),
  'signatures.maxLines': def({
    section: 'signatures',
    schema: z.number().int().min(1).max(50),
    default: 5,
    label: 'İmza en fazla satır',
    input: 'number',
    public: true,
  }),

  // Uyarılar
  'warnings.enabled': def({
    section: 'warnings',
    schema: z.boolean(),
    default: true,
    label: 'Uyarı sistemi açık',
    input: 'boolean',
    public: true,
  }),
  'warnings.maxPoints': def({
    section: 'warnings',
    schema: z.number().int().min(1).max(1000),
    default: 100,
    label: 'Maksimum uyarı puanı',
    description: 'Uyarı çubuğu bu değere göre dolar.',
    input: 'number',
    public: true,
  }),
  'warnings.showLevelPublicly': def({
    section: 'warnings',
    schema: z.boolean(),
    default: false,
    label: 'Uyarı seviyesini herkese göster',
    input: 'boolean',
    public: true,
  }),

  // Başarılar
  'achievements.enabled': def({
    section: 'achievements',
    schema: z.boolean(),
    default: true,
    label: 'Başarı sistemi açık',
    input: 'boolean',
    public: true,
  }),
  'achievements.featuredMax': def({
    section: 'achievements',
    schema: z.number().int().min(0).max(20),
    default: 5,
    label: 'Profilde öne çıkarılabilecek başarı sayısı',
    input: 'number',
    public: true,
  }),

  // Forum
  'forum.topicsPerPage': def({
    section: 'forum',
    schema: z.number().int().min(5).max(100),
    default: 20,
    label: 'Sayfa başına konu',
    input: 'number',
    public: true,
  }),
  'forum.postsPerPage': def({
    section: 'forum',
    schema: z.number().int().min(5).max(100),
    default: 15,
    label: 'Sayfa başına mesaj',
    input: 'number',
    public: true,
  }),
  'forum.titleMaxLength': def({
    section: 'forum',
    schema: z.number().int().min(20).max(150),
    default: 100,
    label: 'Konu başlığı en fazla karakter',
    input: 'number',
    public: true,
  }),
  'forum.postMaxLength': def({
    section: 'forum',
    schema: z.number().int().min(100).max(200000),
    default: 30000,
    label: 'Mesaj en fazla karakter',
    input: 'number',
    public: true,
  }),
  'forum.floodSeconds': def({
    section: 'forum',
    schema: z.number().int().min(0).max(600),
    default: 10,
    label: 'İki mesaj arasında bekleme süresi (saniye)',
    description: 'Moderatörler bu sınırdan etkilenmez. 0 = kapalı.',
    input: 'number',
  }),
  'forum.editWindowMinutes': def({
    section: 'forum',
    schema: z.number().int().min(0).max(525600),
    default: 0,
    label: 'Kendi mesajını düzenleme süresi (dakika)',
    description: '0 = süresiz. Moderatörler bu sınırdan etkilenmez.',
    input: 'number',
    public: true,
  }),
  'forum.editGraceSeconds': def({
    section: 'forum',
    schema: z.number().int().min(0).max(3600),
    default: 60,
    label: '"Düzenlendi" notu için tolerans (saniye)',
    description: 'Mesaj gönderildikten sonraki bu süre içindeki düzenlemeler işaretlenmez ve geçmişe yazılmaz.',
    input: 'number',
  }),
  'forum.hotTopicReplies': def({
    section: 'forum',
    schema: z.number().int().min(1).max(10000),
    default: 25,
    label: 'Popüler konu eşiği (yanıt sayısı)',
    input: 'number',
    public: true,
  }),
  'forum.maxQuoteDepth': def({
    section: 'forum',
    schema: z.number().int().min(1).max(10),
    default: 3,
    label: 'İç içe alıntı sınırı',
    input: 'number',
  }),
  'forum.imageMaxKb': def({
    section: 'forum',
    schema: z.number().int().min(50).max(20480),
    default: 4096,
    label: 'Mesaj görseli en fazla boyut (KB)',
    input: 'number',
    public: true,
  }),
  'forum.tagsEnabled': def({
    section: 'forum',
    schema: z.boolean(),
    default: true,
    label: 'Konu etiketleri',
    description: 'Konulara etiket eklenebilir; etiket sayfaları ve aramada etiket filtresi açılır.',
    input: 'boolean',
    public: true,
  }),
  'forum.tagsMax': def({
    section: 'forum',
    schema: z.number().int().min(1).max(10),
    default: 5,
    label: 'Konu başına en fazla etiket',
    input: 'number',
    public: true,
  }),
  'forum.tagsAllowNew': def({
    section: 'forum',
    schema: z.boolean(),
    default: true,
    label: 'Üyeler yeni etiket oluşturabilir',
    description: 'Kapalıysa yalnızca var olan etiketler seçilebilir (moderatörler her zaman oluşturabilir).',
    input: 'boolean',
    public: true,
  }),
  'forum.pollMaxOptions': def({
    section: 'forum',
    schema: z.number().int().min(2).max(20),
    default: 10,
    label: 'Ankette en fazla seçenek',
    input: 'number',
    public: true,
  }),
  // Görünüm
  'appearance.themeStyle': def({
    section: 'appearance',
    schema: z.enum(THEME_STYLES),
    default: 'modern' as ThemeStyle,
    label: 'Tema',
    description: 'Forumun temel düzeni: Modern ya da Topluluk (bannerlı üst alan, altında menü).',
    input: 'select',
    options: [
      { value: 'modern', label: 'Modern' },
      { value: 'community', label: 'Topluluk' },
    ],
    public: true,
  }),
  'appearance.radius': def({
    section: 'appearance',
    schema: z.enum(['auto', 'none', 'sm', 'md', 'lg', 'xl']),
    default: 'auto' as 'auto' | 'none' | 'sm' | 'md' | 'lg' | 'xl',
    label: 'Köşe yuvarlaklığı',
    description: 'Buton, kart ve kutuların köşeleri. "Temaya göre" seçilirse temanın kendi değeri kullanılır.',
    input: 'select',
    options: [
      { value: 'auto', label: 'Temaya göre' },
      { value: 'none', label: 'Köşeli' },
      { value: 'sm', label: 'Az yuvarlak' },
      { value: 'md', label: 'Orta' },
      { value: 'lg', label: 'Yuvarlak' },
      { value: 'xl', label: 'Çok yuvarlak' },
    ],
    public: true,
  }),
  'appearance.postLayout': def({
    section: 'appearance',
    schema: z.enum(['side', 'top']),
    default: 'top' as 'side' | 'top',
    label: 'Mesaj düzeni',
    description: 'Konularda yazar bilgisinin yeri: solda sütun (klasik) ya da mesajın üstünde yatay şerit.',
    input: 'select',
    options: [
      { value: 'side', label: 'Yazar solda (sütun)' },
      { value: 'top', label: 'Yazar üstte (yatay)' },
    ],
    public: true,
  }),
  'appearance.authLayout': def({
    section: 'appearance',
    schema: z.enum(['split', 'centered', 'cover']),
    default: 'split' as 'split' | 'centered' | 'cover',
    label: 'Giriş ve kayıt sayfası düzeni',
    description: 'Bölünmüş (bir yanda görsel), ortada kart ya da tam ekran arka plan üzerinde kart.',
    input: 'select',
    options: [
      { value: 'split', label: 'Bölünmüş' },
      { value: 'centered', label: 'Ortada kart' },
      { value: 'cover', label: 'Tam ekran' },
    ],
    public: true,
  }),
  'appearance.authImageSide': def({
    section: 'appearance',
    schema: z.enum(['left', 'right']),
    default: 'left' as 'left' | 'right',
    label: 'Giriş sayfasında görselin yeri',
    input: 'select',
    options: [
      { value: 'left', label: 'Solda' },
      { value: 'right', label: 'Sağda' },
    ],
    public: true,
  }),
  'appearance.authHeadline': def({
    section: 'appearance',
    schema: z.string().trim().max(120),
    default: '',
    label: 'Giriş sayfası başlığı',
    description: 'Görsel alanında büyük yazı; boşsa "{forum} topluluğuna hoş geldin".',
    input: 'text',
    public: true,
  }),
  'appearance.authText': def({
    section: 'appearance',
    schema: z.string().trim().max(300),
    default: '',
    label: 'Giriş sayfası alt yazısı',
    description: 'Başlığın altındaki kısa metin; boşsa forum açıklaması kullanılır.',
    input: 'textarea',
    public: true,
  }),
  'appearance.defaultMode': def({
    section: 'appearance',
    schema: z.enum(['dark', 'light', 'system']),
    default: 'dark' as 'dark' | 'light' | 'system',
    label: 'Varsayılan renk modu',
    description: 'Tercih yapmamış ziyaretçilere gösterilen mod.',
    input: 'select',
    options: [
      { value: 'dark', label: 'Koyu' },
      { value: 'light', label: 'Açık' },
      { value: 'system', label: 'Cihaz ayarına göre' },
    ],
    public: true,
  }),
  'appearance.accentColor': def({
    section: 'appearance',
    schema: z.string().regex(/^#[0-9a-fA-F]{6}$/, 'Renk #RRGGBB biçiminde olmalı.'),
    default: '#9c9c9c',
    label: 'Vurgu rengi',
    description: 'Butonlar, bağlantılar ve öne çıkan öğelerin rengi (#RRGGBB).',
    input: 'text',
    public: true,
  }),
  'appearance.colorSpread': def({
    section: 'appearance',
    schema: z.enum(['none', 'soft', 'medium', 'strong']),
    default: 'none' as 'none' | 'soft' | 'medium' | 'strong',
    label: 'Renk yayılımı',
    description: 'Vurgu renginin arka plan, kart, kenarlık ve üst alana ne kadar yansıyacağı.',
    input: 'select',
    options: [
      { value: 'none', label: 'Yalnızca butonlar ve bağlantılar' },
      { value: 'soft', label: 'Hafif' },
      { value: 'medium', label: 'Belirgin' },
      { value: 'strong', label: 'Güçlü' },
    ],
    public: true,
  }),
  'appearance.bannerEnabled': def({
    section: 'appearance',
    schema: z.boolean(),
    default: true,
    label: 'Banner göster',
    description: 'Üst alanda logolu banner. Görsel yüklenmemişse vurgu renginden bir desen kullanılır.',
    input: 'boolean',
    public: true,
  }),
  'appearance.bannerColor': def({
    section: 'appearance',
    schema: z.string().regex(/^#[0-9a-fA-F]{6}$/, 'Renk #RRGGBB biçiminde olmalı.'),
    default: '#16171b',
    label: 'Banner rengi',
    description: 'Banner görseli yüklenmediyse banner bu düz renkte gösterilir (#RRGGBB).',
    input: 'text',
    public: true,
  }),
  'appearance.bannerTagline': def({
    section: 'appearance',
    schema: z.string().trim().max(160),
    default: '',
    label: 'Banner alt yazısı',
    description: 'Bannerda logonun altında görünen kısa slogan. Boş bırakılırsa yazı gösterilmez.',
    input: 'text',
    public: true,
  }),
  'appearance.showForumName': def({
    section: 'appearance',
    schema: z.boolean(),
    default: false,
    label: 'Logonun yanında forum adını göster',
    input: 'boolean',
    public: true,
  }),
  'appearance.bannerHeight': def({
    section: 'appearance',
    schema: z.number().int().min(80).max(400),
    default: 160,
    label: 'Banner yüksekliği (px)',
    description: 'Banner görseli yüklendiyse üst alanın yüksekliği.',
    input: 'number',
    public: true,
  }),
  'appearance.backgroundDim': def({
    section: 'appearance',
    schema: z.number().int().min(0).max(95),
    default: 80,
    label: 'Arka plan karartma (%)',
    description: 'Sayfa arka plan görselinin üzerine tema renginde uygulanan örtü; yazıların okunaklı kalması için.',
    input: 'number',
    public: true,
  }),
  'appearance.welcomeEnabled': def({
    section: 'appearance',
    schema: z.boolean(),
    default: true,
    label: 'Ana sayfada karşılama alanı',
    description: 'Giriş yapmamış ziyaretçilere ana sayfanın üstünde başlık, açıklama ve kayıt düğmesi gösterilir.',
    input: 'boolean',
    public: true,
  }),
  'appearance.welcomeTitle': def({
    section: 'appearance',
    schema: z.string().trim().max(120),
    default: '',
    label: 'Karşılama başlığı',
    description: 'Boş bırakılırsa "Forum adına hoş geldin" yazılır.',
    input: 'text',
    public: true,
  }),
  'appearance.welcomeText': def({
    section: 'appearance',
    schema: z.string().trim().max(400),
    default: '',
    label: 'Karşılama metni',
    description: 'Boş bırakılırsa forum açıklaması kullanılır.',
    input: 'textarea',
    public: true,
  }),
  'appearance.footerText': def({
    section: 'appearance',
    schema: z.string().trim().max(500),
    default: '',
    label: 'Alt bilgi metni',
    description: 'Alt bilginin sağ alt köşesinde görünür (telif, tema veya emeği geçenler). Boş bırakılırsa "© yıl forum adı" yazılır.',
    input: 'textarea',
    public: true,
  }),
  'appearance.footerLinks': def({
    section: 'appearance',
    schema: z.array(z.object({ label: z.string().trim().min(1, 'Ad gerekli.').max(40), url: footerLinkUrl, newTab: z.boolean().default(false) })).max(12),
    default: [
      { label: 'Forum Kuralları', url: '/policies/rules', newTab: false },
      { label: 'Kullanım Koşulları', url: '/policies/terms', newTab: false },
      { label: 'Gizlilik Politikası', url: '/policies/privacy', newTab: false },
      { label: 'Çerezler', url: '/cookies', newTab: false },
    ] as Array<{ label: string; url: string; newTab: boolean }>,
    label: 'Alt bilgi bağlantıları',
    input: 'list',
    public: true,
    hidden: true,
  }),
  'appearance.fontFamily': def({
    section: 'appearance',
    schema: z.enum(FONT_OPTIONS.map((f) => f.key) as [FontKey, ...FontKey[]]),
    default: 'inter' as FontKey,
    label: 'Yazı tipi',
    input: 'select',
    options: FONT_OPTIONS.map((f) => ({ value: f.key, label: f.label })),
    public: true,
  }),
  'appearance.logoUrl': def({ section: 'appearance', schema: assetUrl, default: '/brand/inkforum-wordmark-light.png' as string | null, label: 'Logo', input: 'text', public: true, hidden: true }),
  'appearance.logoLightUrl': def({ section: 'appearance', schema: assetUrl, default: '/brand/inkforum-wordmark-dark.png' as string | null, label: 'Açık mod logosu', input: 'text', public: true, hidden: true }),
  'appearance.faviconUrl': def({ section: 'appearance', schema: assetUrl, default: '/brand/inkforum-icon-192.png' as string | null, label: 'Site simgesi', input: 'text', public: true, hidden: true }),
  'appearance.bannerUrl': def({ section: 'appearance', schema: assetUrl, default: null as string | null, label: 'Banner görseli', input: 'text', public: true, hidden: true }),
  'appearance.authImageUrl': def({ section: 'appearance', schema: assetUrl, default: null as string | null, label: 'Giriş / kayıt görseli', input: 'text', public: true, hidden: true }),
  'appearance.footerBgUrl': def({ section: 'appearance', schema: assetUrl, default: null as string | null, label: 'Alt bilgi arka planı', input: 'text', public: true, hidden: true }),
  'appearance.backgroundUrl': def({ section: 'appearance', schema: assetUrl, default: null as string | null, label: 'Sayfa arka planı', input: 'text', public: true, hidden: true }),
  'appearance.defaultAvatarUrl': def({ section: 'appearance', schema: assetUrl, default: null as string | null, label: 'Varsayılan avatar', input: 'text', public: true, hidden: true }),
  'appearance.socialLinks': def({
    section: 'appearance',
    schema: z
      .array(z.object({ platform: z.string().max(20), url: z.string().trim().regex(/^https?:\/\//, 'Bağlantı http(s):// ile başlamalı.').max(500) }))
      .max(20),
    default: [] as Array<{ platform: string; url: string }>,
    label: 'Sosyal medya bağlantıları',
    input: 'list',
    public: true,
    hidden: true,
  }),

  // Özel mesajlar
  'messages.enabled': def({
    section: 'messages',
    schema: z.boolean(),
    default: true,
    label: 'Özel mesajlar açık',
    description: 'Kapalıyken yeni konuşma başlatılamaz ve yanıt yazılamaz; mevcut konuşmalar okunabilir.',
    input: 'boolean',
    public: true,
  }),
  'messages.maxRecipients': def({
    section: 'messages',
    schema: z.number().int().min(1).max(50),
    default: 10,
    label: 'Bir konuşmadaki en fazla katılımcı',
    description: 'Başlatan üye hariç.',
    input: 'number',
    public: true,
  }),
  'messages.maxLength': def({
    section: 'messages',
    schema: z.number().int().min(100).max(50000),
    default: 10000,
    label: 'Mesaj uzunluğu sınırı (karakter)',
    input: 'number',
    public: true,
  }),
  'messages.floodSeconds': def({
    section: 'messages',
    schema: z.number().int().min(0).max(300),
    default: 5,
    label: 'İki mesaj arasındaki en kısa süre (sn)',
    input: 'number',
  }),
  'messages.newPerHour': def({
    section: 'messages',
    schema: z.number().int().min(1).max(500),
    default: 20,
    label: 'Saatte başlatılabilecek yeni konuşma sayısı',
    description: 'Yöneticiler ve moderatörler bu sınıra tabi değildir.',
    input: 'number',
  }),

  // Çerezler
  'cookies.bannerEnabled': def({
    section: 'cookies',
    schema: z.boolean(),
    default: true,
    label: 'Çerez bilgilendirmesini göster',
    input: 'boolean',
    public: true,
  }),
  'cookies.bannerText': def({
    section: 'cookies',
    schema: z.string().trim().min(1).max(1000),
    default: 'Bu site oturumunuzu ve tercihlerinizi hatırlamak için yalnızca gerekli çerezleri kullanır. Gömülü içerikler (YouTube, Spotify vb.) kendi çerezlerini kullanabilir.',
    label: 'Çerez bilgilendirme metni',
    input: 'textarea',
    public: true,
  }),

  // Gömülü içerik: "Yönetim → Gömülü içerik" ekranından yönetilir (kaydedilince mesajlar yeniden işlenir).
  'embeds.enabled': def({
    section: 'forum',
    schema: z.boolean(),
    default: true,
    label: 'Gömülü içerik (YouTube, Spotify, X…) açık',
    input: 'boolean',
    public: true,
    hidden: true,
  }),
  'embeds.autoEmbed': def({
    section: 'forum',
    schema: z.boolean(),
    default: true,
    label: 'Tek satırdaki bağlantıları otomatik göm',
    input: 'boolean',
    public: true,
    hidden: true,
  }),
  'embeds.clickToLoad': def({
    section: 'forum',
    schema: z.boolean(),
    default: false,
    label: 'Gömülü içerik tıklanınca yüklensin (gizlilik)',
    input: 'boolean',
    hidden: true,
  }),
  'embeds.disabledProviders': def({
    section: 'forum',
    schema: z.array(z.string().max(40)).max(100),
    default: [] as string[],
    label: 'Kapalı sağlayıcılar',
    input: 'list',
    hidden: true,
  }),
  'embeds.custom': def({
    section: 'forum',
    schema: z
      .array(
        z.object({
          key: z.string().regex(/^[a-z0-9-]{2,40}$/),
          name: z.string().trim().min(1).max(60),
          pattern: z.string().min(3).max(300),
          template: z.string().min(10).max(500),
          ratio: z.string().regex(/^\d{1,2}\/\d{1,2}$/).nullable().optional(),
          height: z.number().int().min(80).max(1200).nullable().optional(),
          maxWidth: z.number().int().min(200).max(1200).nullable().optional(),
          enabled: z.boolean().optional(),
        }),
      )
      .max(50),
    default: [] as Array<{ key: string; name: string; pattern: string; template: string; ratio?: string | null; height?: number | null; maxWidth?: number | null; enabled?: boolean }>,
    label: 'Özel sağlayıcılar',
    input: 'list',
    hidden: true,
  }),

  // Geliştirici platformu (Yönetim → Geliştiriciler)
  'oauth.accessTokenMinutes': def({
    section: 'security',
    schema: z.number().int().min(5).max(1440),
    default: 60,
    label: 'OAuth erişim belirteci süresi (dakika)',
    input: 'number',
  }),
  'oauth.refreshTokenDays': def({
    section: 'security',
    schema: z.number().int().min(1).max(365),
    default: 30,
    label: 'OAuth yenileme belirteci süresi (gün)',
    input: 'number',
  }),
  'social.providers': def({
    section: 'security',
    schema: z.record(z.string(), z.object({ enabled: z.boolean(), clientId: z.string(), clientSecret: z.string() })),
    default: {} as Record<string, { enabled: boolean; clientId: string; clientSecret: string }>,
    label: 'Sosyal giriş sağlayıcıları',
    input: 'list',
    hidden: true,
  }),

  // Özel kod ve entegrasyonlar (Yönetim → Özel kod ekranından düzenlenir)
  'custom.enabled': def({
    section: 'appearance',
    schema: z.boolean(),
    default: true,
    label: 'Özel kod parçacıkları çalışsın',
    input: 'boolean',
    hidden: true,
  }),
  'custom.css': def({
    section: 'appearance',
    schema: z.string().max(100_000),
    default: '',
    label: 'Özel CSS',
    input: 'textarea',
    hidden: true,
  }),
  'custom.csp': def({
    section: 'appearance',
    schema: z.object({ script: z.array(z.string()), connect: z.array(z.string()), style: z.array(z.string()), font: z.array(z.string()) }),
    default: { script: [], connect: [], style: [], font: [] } as { script: string[]; connect: string[]; style: string[]; font: string[] },
    label: 'İzin verilen dış kaynaklar',
    input: 'list',
    hidden: true,
  }),
  'custom.tokenTtl': def({
    section: 'appearance',
    schema: z.number().int().min(30).max(3600),
    default: 300,
    label: 'Entegrasyon belirteci süresi (sn)',
    input: 'number',
    hidden: true,
  }),
  'integration.secret': def({
    section: 'security',
    schema: z.string().max(200),
    default: '',
    label: 'Entegrasyon imza anahtarı',
    input: 'text',
    hidden: true,
  }),

  // İç durum
  'policies.epoch': def({
    section: 'general',
    schema: z.number().int().min(0),
    default: 0,
    label: 'Politika dönemi',
    input: 'number',
    hidden: true,
  }),
} as const;

export type SettingKey = keyof typeof SETTINGS;
export type SettingsValues = { [K in SettingKey]: z.infer<(typeof SETTINGS)[K]['schema']> };
export type PublicSettings = Partial<SettingsValues>;

export const SETTING_KEYS = Object.keys(SETTINGS) as SettingKey[];

export function settingDefaults(): SettingsValues {
  const out: Record<string, unknown> = {};
  for (const key of SETTING_KEYS) out[key] = JSON.parse(JSON.stringify(SETTINGS[key].default));
  return out as SettingsValues;
}
