import { t } from '$lib/i18n.svelte';

const LABELS: Record<string, string> = {
  'achievement.award': 'başarı verdi',
  'achievement.revoke': 'başarı geri aldı',
  'achievement.create': 'başarı oluşturdu',
  'achievement.update': 'başarıyı düzenledi',
  'achievement.delete': 'başarıyı sildi',
  'achievement.backfill': 'başarıları yeniden hesapladı',
  'appearance.nav': 'üst menüyü düzenledi',
  'appearance.social': 'sosyal bağlantıları düzenledi',
  'appearance.footer': 'alt bilgiyi düzenledi',
  'ban.create': 'yasak ekledi',
  'ban.update': 'yasağı düzenledi',
  'ban.lift': 'yasağı kaldırdı',
  'ban.delete': 'yasağı sildi',
  'embeds.update': 'gömülü içerik ayarlarını değiştirdi',
  'forum.board.create': 'bölüm oluşturdu',
  'forum.board.update': 'bölümü düzenledi',
  'forum.board.delete': 'bölümü sildi',
  'forum.board.icon': 'bölüm ikonunu değiştirdi',
  'forum.board.moderators': 'bölüm moderatörlerini değiştirdi',
  'forum.category.create': 'kategori oluşturdu',
  'forum.category.update': 'kategoriyi düzenledi',
  'forum.category.delete': 'kategoriyi sildi',
  'forum.category.background': 'kategori arka planını değiştirdi',
  'forum.prefix.create': 'önek oluşturdu',
  'forum.prefix.update': 'öneki düzenledi',
  'forum.prefix.delete': 'öneki sildi',
  'forum.recount': 'sayaçları yeniledi',
  'forum.reorder': 'forum sırasını değiştirdi',
  'group.create': 'grup oluşturdu',
  'group.update': 'grubu düzenledi',
  'group.delete': 'grubu sildi',
  'group.member_add': 'gruba üye ekledi',
  'group.member_remove': 'gruptan üye çıkardı',
  'home.layout': 'ana sayfa düzenini değiştirdi',
  'tag.create': 'etiket oluşturdu',
  'tag.update': 'etiketi düzenledi',
  'tag.delete': 'etiketi sildi',
  'emoji.create': 'özel emoji ekledi',
  'emoji.update': 'özel emojiyi düzenledi',
  'emoji.delete': 'özel emojiyi sildi',
  'mail.template.update': 'e-posta şablonunu düzenledi',
  'mail.template.reset': 'e-posta şablonunu varsayılana döndürdü',
  'forum.board.cover': 'bölüm kapak fotoğrafını değiştirdi',
  'forum.board.cover.remove': 'bölüm kapak fotoğrafını kaldırdı',
  'oauth.client.create': 'OAuth uygulaması oluşturdu',
  'oauth.client.update': 'OAuth uygulamasını düzenledi',
  'oauth.client.secret': 'OAuth uygulamasının anahtarını yeniledi',
  'oauth.client.delete': 'OAuth uygulamasını sildi',
  'apikey.create': 'API anahtarı oluşturdu',
  'apikey.revoke': 'API anahtarını iptal etti',
  'webhook.create': 'webhook ekledi',
  'webhook.update': 'webhook düzenledi',
  'webhook.secret': 'webhook anahtarını yeniledi',
  'webhook.delete': 'webhook sildi',
  'social.providers': 'sosyal giriş ayarlarını değiştirdi',
  'custom.page.create': 'özel sayfa oluşturdu',
  'custom.page.update': 'özel sayfayı düzenledi',
  'custom.page.delete': 'özel sayfayı sildi',
  'extension.install': 'eklenti kurdu',
  'extension.update': 'eklentiyi güncelledi',
  'extension.enable': 'eklentiyi açtı',
  'extension.disable': 'eklentiyi kapattı',
  'extension.uninstall': 'eklentiyi kaldırdı',
  'extension.settings': 'eklenti ayarlarını değiştirdi',
  'notification.broadcast': 'toplu bildirim gönderdi',
  'permissions.update': 'yetkileri değiştirdi',
  'permissions.copy': 'yetkileri kopyaladı',
  'permissions.profile.create': 'yetki profili oluşturdu',
  'permissions.profile.update': 'yetki profilini düzenledi',
  'permissions.profile.values': 'yetki profilini değiştirdi',
  'policy.create': 'politika oluşturdu',
  'policy.update': 'politikayı düzenledi',
  'policy.publish': 'politika sürümü yayımladı',
  'post.approve': 'mesaj onayladı',
  'post.delete': 'mesaj sildi',
  'post.edit': 'mesaj düzenledi',
  'post.restore': 'mesajı geri getirdi',
  'profile_field.create': 'profil alanı ekledi',
  'profile_field.update': 'profil alanını düzenledi',
  'settings.update': 'ayarları değiştirdi',
  'topic.delete': 'konu sildi',
  'topic.edit': 'konuyu düzenledi',
  'topic.merge': 'konuları birleştirdi',
  'topic.move': 'konu taşıdı',
  'topic.restore': 'konuyu geri getirdi',
  'topic.hide': 'konuyu gizledi',
  'topic.unhide': 'konuyu görünür yaptı',
  'topic.member.add': 'gizli konuya üye ekledi',
  'topic.member.remove': 'gizli konudan üye çıkardı',
  'user.approve': 'üyeliği onayladı',
  'user.reject': 'üyeliği reddetti',
  'user.delete': 'üye sildi',
  'user.edit': 'üyeyi düzenledi',
  'user.groups': 'üyenin gruplarını değiştirdi',
  'user.username_change': 'kullanıcı adını değiştirdi',
  'warning.issue': 'uyarı verdi',
  'warning.revoke': 'uyarıyı geri aldı',
  moderate: 'moderasyon işlemi yaptı',
  mute: 'üyeyi susturdu',
  temp_ban: 'geçici yasak verdi',
  watch: 'üyeyi izlemeye aldı',
  'warning_action.create': 'uyarı yaptırımı ekledi',
  'profile_field.delete': 'profil alanını sildi',
  'group.moderators': 'grup moderatörlerini değiştirdi',
  'permissions.profile.delete': 'yetki profilini sildi',
  'user.email_change': 'e-posta adresini değiştirdi',
  'user.email_verified': 'e-posta adresini doğruladı',
  'user.profile_edit': 'profili düzenledi',
  'user.register': 'kayıt oldu',
  'user.sessions_revoke': 'oturumları kapattı',
  login: 'giriş yaptı',
  'login.failed': 'başarısız giriş denemesi',
  'session.elevated': 'yönetim oturumunu doğruladı',
  'sessions.revoke_others': 'diğer oturumları kapattı',
  'password.changed': 'şifresini değiştirdi',
  'password.reset': 'şifresini sıfırladı',
  'password.reset_requested': 'şifre sıfırlama istedi',
  'maintenance.run_tasks': 'bakım görevlerini çalıştırdı',
};

export function auditLabel(action: string): string {
  if (LABELS[action]) return t(LABELS[action]);
  if (action.startsWith('appearance.')) return action.endsWith('.remove') ? t('görünüm görselini kaldırdı') : t('görünüm görselini değiştirdi');
  if (action.startsWith('maintenance.')) return t('bakım görevi çalıştırdı');
  return action;
}
